#!/usr/bin/env node
/**
 * Build-time config injection.
 *
 * Reads SUPABASE_URL and SUPABASE_ANON from process.env, then writes
 * site/config.local.js so the static HTML can read them at runtime via
 * window.APP_CONFIG.
 *
 * On Vercel: env vars come from the project's Environment Variables.
 * Locally:   set them in your shell, or hand-edit site/config.local.js
 *            directly (it's gitignored either way).
 *
 * Used by vercel.json's buildCommand.
 */
const fs = require('fs');
const path = require('path');

const required = ['SUPABASE_URL', 'SUPABASE_ANON'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`[build-config] Missing required env vars: ${missing.join(', ')}`);
  console.error('  On Vercel: set them in Project Settings → Environment Variables');
  console.error('  Locally:   export them in your shell, or hand-edit site/config.local.js');
  process.exit(1);
}

const out = path.join(__dirname, '..', 'site', 'config.local.js');
const contents = `/*
 * GENERATED by scripts/build-config.js — do not edit by hand on Vercel.
 * Locally, you can either re-run the script or hand-edit this file
 * (it's gitignored). Source values: env vars SUPABASE_URL, SUPABASE_ANON.
 */
window.APP_CONFIG = {
  SUPABASE_URL:  ${JSON.stringify(process.env.SUPABASE_URL)},
  SUPABASE_ANON: ${JSON.stringify(process.env.SUPABASE_ANON)},
};
`;

fs.writeFileSync(out, contents);
console.log(`[build-config] Wrote ${path.relative(process.cwd(), out)}`);
